### PR TITLE
Obrazek > Obraz

### PR DESCRIPTION
**Pull request by piotrdrag**
CC @adrianer for changes in suite.

### CODE REVIEW

**Comment by adrianer** [comment]
For the suite part r+ from me, even though I don't really like this change. Nonetheless: if the rest of Mozilla will do it, so will suite.

BTW. Were there really no appearances of "image" in extensions/irc?

**Comment by piotrdrag** [comment]
The only one I've found is: "pref.munger.face.help=Włącza wyświetlanie przez ChatZillę obrazków dla najpopularniejszych uśmieszków (emotikonek), takich jak :-) i ;-)."

I believe that, in this specific instance, "obrazek" actually fits better.

**Comment by splewako** [comment]
> even though I don't really like this change

is it something more than personal preference?

**Comment by adrianer** [comment]
> is it something more than personal preference?

It's more than just that - but I'm not sure, if my explanation also applies outside of Upper Silesia: if you have an image hanging on the wall that is bigger than about the A2/A3 format, you call it "obraz". If it's smaller than that, it's "obrazek". So unless you have a 32 inch display (or bigger), the size of anything on the display won't be big enough to call it "obraz". Is it the same in the rest of Poland or is it an Upper Silesian thing? ;)

**Comment by splewako** [comment]
> It's more than just that - but I'm not sure, if my explanation also applies outside of Upper Silesia: if you have an image hanging on the wall that is bigger than about the A2/A3 format, you call it "obraz". If it's smaller than that, it's "obrazek". So unless you have a 32 inch display (or bigger), the size of anything on the display won't be big enough to call it "obraz". Is it the same in the rest of Poland or is it an Upper Silesian thing? ;)

I haven't heard about such specific rule honestly, "obrazek" being simply diminutive form of "obraz".

**Comment by splewako** [comment]
Landed as https://hg.mozilla.org/l10n-central/pl/pushloghtml?changeset=f7daca1570ff then, thank you for the patches.

**Pull request closed without merging**
