### PR TITLE
Typos and other improvements 160126

### PR DESCRIPTION
**Pull request by piotrdrag**
If accepted, I'll update also PR #45 with the changes.

### CODE REVIEW

**Comment by piotrdrag** [comment]
It would be great to push at least the first two commits - they are a simple typo fix and a missing commas fix.

**Comment by splewako** [comment]
Yes, sorry for the delay - I will do something about this later today.

**Comment by splewako** [comment]
> If accepted, I'll update also PR #45 with the changes.

I wouldn't invest to much time in updating suite pull requests.

**Comment by splewako** [comment]
Landed few:
- [Typos in inspector.nodePreview.selectNodeLabel and inspector.nodePreview.highlightNodeLabel](https://github.com/aviarypl/mozilla-l10n-central-pl/commit/2fac35c1dd3dea52d162ffcfb3095628ba5f96ab)
- [Missing commas in css.properties and messenger.properties ](https://github.com/aviarypl/mozilla-l10n-central-pl/commit/1237f51aab3cc9f21408f8deba9418b7b32cfad0)
- [Unify "command" translations to "polecenie" ](https://github.com/aviarypl/mozilla-l10n-central-pl/commit/2913dd95bfd91103afca150d1dd9b21201e8a1c1)
- [Unify "action" translations to "czynność"](https://github.com/aviarypl/mozilla-l10n-central-pl/commit/77aeb86c9b0fa9c11fee3ab267b233cc484441e0)

**Comment by splewako** [comment]
For unifying "acceleration" translations I would prefer "sprzętowego przyspiesz**a**nia", for "update" the form "**u**aktualnić". Commit about unifying "current" translations has misleading commit message but I otherwise like the change I guess.

I don't believe that "status" and "stan" mean the same thing, the same goes for "operacja" and "działanie".

**Comment by piotrdrag** [comment]
> For unifying "acceleration" translations I would prefer "sprzętowego przyspieszania",

Changed.

> for "update" the form "uaktualnić".

I really dislike that one. But if you want to do it, go ahead.

> Commit about unifying "current" translations has misleading commit message but I otherwise like the change I guess.

If you mean the word "unify", then it's fixed.

> I don't believe that "status" and "stan" mean the same thing, the same goes for "operacja" and "działanie".

I believe "stan" is a better translation of English "status" in our cases, same for "działanie" for English "operation".

**Comment by splewako** [comment]
- [Unify "acceleration" translations to "przyspieszanie"](https://github.com/aviarypl/mozilla-l10n-central-pl/commit/a772b2020ea0d558ed3e7eddb69007ee805c05fa)
- [Change "current" translations to "bieżący" or "obecnie"](https://github.com/aviarypl/mozilla-l10n-central-pl/commit/c10398ac763cd3cfb146f0a53f767d0205dcb003)

**Comment by splewako** [comment]
> > for "update" the form "uaktualnić".
> 
> I really dislike that one. But if you want to do it, go ahead.

Also in `mobile/`?

**Comment by piotrdrag** [comment]
> > > for "update" the form "uaktualnić".
> > 
> > I really dislike that one. But if you want to do it, go ahead.
> 
> Also in mobile/?

I'd prefer not, the current translation is in line with Android's translation.

**Comment by splewako** [comment]
No problem, https://github.com/aviarypl/mozilla-l10n-central-pl/commit/ceeb585dd214f10349954a2029f6f800e21a0039

I'm closing this pull request and as for the rest (unifying "operation" and "status" translations) I would suggest discussing them on [community-poland](https://mail.mozilla.org/listinfo/community-poland) first.

**Pull request closed without merging**
