### PR TITLE
Testing pull requests

### PR DESCRIPTION
**Pull request by splewako**

### CODE REVIEW

**Comment by splewako** [comment]
https://github.com/aviarypl/mozilla-l10n-central-pl/pull/84/commits/e6f89146fa134e6e747341e9ee1641abdf12f721 landed as https://github.com/aviarypl/mozilla-l10n-central-pl/commit/e5d3cb7dc998709ba123117a9eb864ca1e0a18f4 and https://hg.mozilla.org/l10n-central/pl/rev/7d2ff8e35f90 using `curl --location https://github.com/aviarypl/mozilla-l10n-central-pl/pull/84.patch | git am`

**Comment by splewako** [comment]
Simple pulling updated upstream straight to the pull source fails.

`git pull --rebase git@github.com:aviarypl/mozilla-l10n-central-pl.git` works for fork clone but still requires forced update `git push --force` to the pull request source. Such forced update seems to automatically close pull request.

**Comment by splewako** [comment]
Pushing [new change](https://github.com/splewako/mozilla-l10n-central-pl/commit/809f34de842f092a756ed31a35977d5f0987f7b5) to the pull request source doesn't change update pull request automatically.

**Comment by splewako** [comment]
Reopening pull request makes old pushed changes disappear and new change pushed before reopening appear.

**Comment by splewako** [comment]
Force pushing reabsed fork clone with new change updates (rebased changes disappear, new changes appear) pull request without closing it.

**Comment by splewako** [comment]
Possible setup:
1. Fork https://github.com/aviarypl/mozilla-l10n-central-pl
2. Clone https://github.com/aviarypl/mozilla-l10n-central-pl
3. Change push url from original repository to fork (`git remote set-url origin --push --add git@github.com:USER/mozilla-l10n-central-pl.git`) and force push (enabling fork overwriting `git config remote.origin.push '+:'` **doesn't work as expected with pull requests**, needs some other solution).
4. Make changes, push to fork, create pull request.

Since `git pull --rebase` should be used for getting changes by default (and `git pull --rebase && git push` for pushing), there shouldn't be any real differences (from contributor perspective) between writing directly to https://github.com/aviarypl/mozilla-l10n-central-pl and pushing to such persistent pull request?

Advantages for integration: ability to wait for human resolution for changes that potentially break sync between Git and Mercurial (conflicting, unsynchronized, merges?) and much easier implementation.

@piotrdrag: thoughts?

**Comment by piotrdrag** [comment]
Sure, I'm ok with this workflow.

**Comment by splewako** [comment]
OK, I think I have nailed it down. With setup as above (including `remote.origin.push = +:`) `git pull --rebase` will overwrite local changes if they were pushed to fork/pr. Such pull behavior may be surprising and with default forced pushes it may lead to data loss (if the changes from fork/pr were not integrated into main repo yet) but I'm not sure how likely it is and if this is really a problem?

**Comment by splewako** [comment]
Possible next steps if this would real issue:
- find out if it is happening with latest Git
- find a way (config?) to prevent such pull from overwriting pushed changes
- make data loss less likely by shortening the time between pushing the changes to fork/pr and pushing into main repo (initially up to 1h), possibly by [subscribing to Github events](https://developer.github.com/webhooks/)

**Pull request closed without merging**
