### PR TITLE
Unify "absolute" translation to "bezwzględnie"

### PR DESCRIPTION
**Pull request by piotrdrag**
@adrianer

### CODE REVIEW

**Comment by adrianer** [comment]
Venkman is as dead as it can be, so any change to it makes no sense. r- for that part.

This reminds me, that I should remove it completely from the tree some time soon...

**Comment by splewako** [comment]
> Venkman is as dead as it can be, so any change to it makes no sense. r- for that part.
> 
> This reminds me, that I should remove it completely from the tree some time soon...

That is very bad rule and you shouldn't expect anyone to respect it - either it is dead or it is in the tree…

**Comment by adrianer** [comment]
> That is very bad rule and you shouldn't expect anyone to respect it - either it is dead or it is in the tree…

For some time there was a discussion by the SeaMonkey devs to revive it somehow, so I've seen no reason to remove it from the tree at that time. But now, this is off the table, so I'll remove it next time I touch the tree.

**Comment by splewako** [comment]
Thank you for the patch, landed as https://github.com/aviarypl/mozilla-l10n-central-pl/commit/75c619759ddecd2ce28fb2ae5c4d0ac5a9115b1d

**Pull request closed without merging**
