### PR TITLE
Unify "support" translation to "obsługiwać"

### PR DESCRIPTION
**Pull request by piotrdrag**
@adrianer

### CODE REVIEW

**Comment by adrianer** [comment]
r+ for the suite part

**Comment by splewako** [comment]
What with [support website](https://transvision.mozfr.org/?recherche=wsparcia&repo=aurora&sourcelocale=en-US&locale=pl&search_type=strings)?

I would also change "wspierać" in disable-warning.description (webapprt/webapprt/webapp.properties).

**Comment by splewako** [comment]
There is also not that helpful [Aviary.pl bug 1771 - Tłumaczenie "support"](http://bugs.aviary.pl/show_bug.cgi?id=1771)

**Comment by splewako** [comment]
There is also mozilla.org… [wspi](https://transvision.mozfr.org/?recherche=wspi&repo=mozilla_org&sourcelocale=en-US&locale=pl&search_type=strings), [wspar](https://transvision.mozfr.org/?recherche=wspar&repo=mozilla_org&sourcelocale=en-US&locale=pl&search_type=strings) and [support](https://transvision.mozfr.org/?recherche=support&repo=mozilla_org&sourcelocale=en-US&locale=pl&search_type=strings).

**Comment by splewako** [comment]
That shouldn't block landing provided patches however, https://github.com/aviarypl/mozilla-l10n-central-pl/compare/75c619759dde...e005f31ac481 and https://hg.mozilla.org/l10n-central/pl/pushloghtml?changeset=3dfe84abaf86

**Comment by splewako** [comment]
Let's deal with this in https://github.com/aviarypl/team/issues/4

**Pull request closed without merging**
