### PR TITLE
Editor update 160214 

### PR DESCRIPTION
**Pull request by piotrdrag**
Since @adrianer is inactive, I was hoping we could update at least the part that is shared with Thunderbird.

### CODE REVIEW

**Comment by splewako** [comment]
> Since @adrianer is inactive, I was hoping we could update at least the part that is shared with Thunderbird.

Yes, I think it is fair and should be done that way from now on.

To be more specific, `comm-central` `calendar/`, `chat/`, `editor/`, `mail/` and `other-licenses/branding/thunderbird/` (as [backlog](https://www.splewako.com/backlog/mozilla.l10n) suggests) should be considered as part of Thunderbird localization effort (as they are needed to complete it).

**Comment by splewako** [comment]
Thank you for the patch, landed as https://github.com/aviarypl/mozilla-l10n-central-pl/commit/97929f07dd492a01c0bd738a8065bc2221952656 and https://hg.mozilla.org/l10n-central/pl/rev/58471ae50b3c

**Comment by piotrdrag** [comment]
> To be more specific, comm-central calendar/, chat/, editor/, mail/ and other-licenses/branding/thunderbird/ (as backlog suggests) should be considered as part of Thunderbird localization effort (as they are needed to complete it).

Is there a reason why calendar doesn't appear on https://l10n.mozilla.org/dashboard/compare?run=572808?

**Comment by piotrdrag** [comment]
By the way, it would be great if you could push this commit to aurora and beta as well.

**Comment by splewako** [comment]
> > To be more specific, comm-central calendar/, chat/, editor/, mail/ and other-licenses/branding/thunderbird/ (as backlog suggests) should be considered as part of Thunderbird localization effort (as they are needed to complete it).
> 
> Is there a reason why calendar doesn't appear on https://l10n.mozilla.org/dashboard/compare?run=572808?

[Historic](https://blog.mozilla.org/thunderbird/2015/06/thunderbird-38-released/) reasons probably.

**Comment by splewako** [comment]
https://hg.mozilla.org/releases/l10n/mozilla-aurora/pl/rev/1226133fbfb4
https://hg.mozilla.org/releases/l10n/mozilla-beta/pl/rev/0c07df926164

**Pull request closed without merging**
