### PR TITLE
Fix grammar errors

### PR DESCRIPTION
**Pull request by piotrdrag**
It's "liczba" when the subject (or object) is countable.

### CODE REVIEW

**Comment by piotrdrag** [comment]
This also touches files owned by @adrianer.

**Comment by splewako** [comment]
What kind  of grammar error changing "linia" to "wiersz" is fixing?

**Comment by piotrdrag** [comment]
Perhaps I was mistaken to call it a "grammar error". I still believe it's incorrect ([example source](http://portalwiedzy.onet.pl/89066,,,,wiersz_tekstu,haslo.html)).

**Comment by splewako** [comment]
> Perhaps I was mistaken to call it a "grammar error". I still believe it's incorrect ([example source](http://portalwiedzy.onet.pl/89066,,,,wiersz_tekstu,haslo.html)).

Onet? Seriously? I also don't see explanation on that site anyway… but in fact we have decided to use "wiersz" as translation of "line" when used to describe line of text or similar concepts (but not for horizontal line, etc), see [Aviary.pl bug 2730](http://bugs.aviary.pl/show_bug.cgi?id=2730).

Conflicts need to be resolved but otherwise looks good to me now.

@adrianer: r?

**Comment by piotrdrag** [comment]
If you would click on the link you would discover that it references "Słownik Encyklopedyczny - Informatyka" Wydawnictwa Europa. Autor - Zdzisław Płoski. ISBN 83-87977-16-0. Rok wydania 1999.

**Comment by splewako** [comment]
> If you would click on the link you would discover that it references "Słownik Encyklopedyczny - Informatyka" Wydawnictwa Europa. Autor - Zdzisław Płoski. ISBN 83-87977-16-0. Rok wydania 1999.

I think you are not reading what was written. If you would, than you wouldn't assume that I didn't.

Content on the linked page is anonymous work "based" (whatever that means) on referenced book - this should be warning sign for anyone. The content is also full of unexplained assumptions, like "mainly ASCII encoded with optional additions" limitation.

Finally, I see similarly bold to your unexplained "grammar error" and "incorrect" statements without single word of explanation, making me think that this is only about forcing personal preference by greatly escalating, This surprises me even more since I wrote that the change looks good to me.

**Comment by splewako** [comment]
Enough waiting for @adrianer, landed without changes in `extensions/` and `suite/` as https://hg.mozilla.org/l10n-central/pl/pushloghtml?changeset=78a3787e9517 and https://github.com/aviarypl/mozilla-l10n-central-pl/compare/1d11963...46a52e982e66

Thank you for the patches.

**Comment by piotrdrag** [comment]
Closing; there is a version for Adrian in PR #45.

**Pull request closed without merging**
