### PR TITLE
Better translation of "authorization" in suite

### PR DESCRIPTION
**Pull request by piotrdrag**
From the calque "autoryzować" to more Polish "upoważniać". In line with PR#17.

@adrianer

### CODE REVIEW

**Comment by splewako** [comment]
#17 and https://github.com/aviarypl/mozilla-l10n-gaia-pl/pull/8

**Comment by splewako** [comment]
@adrianer: r?

**Comment by adrianer** [comment]
The changed sentence sounds somehow bad, really bad. Maybe instead of "Wystapil blad upowaznienia" try "Wystail blad podczas upowazniania"...?

**Comment by piotrdrag** [comment]
Your version sounds good to me.

**Comment by piotrdrag** [comment]
Changed to "Wystąpił błąd podczas upoważniania."

**Comment by piotrdrag** [comment]
@splewako what about this PR?

**Comment by splewako** [comment]
Landed as https://hg.mozilla.org/l10n-central/pl/rev/79fa494530da and https://github.com/aviarypl/mozilla-l10n-central-pl/commit/f1d9cc2947c530973ae2d45489d5554540beebcd

**Pull request closed without merging**
