### PR TITLE
Fennec weekly update 160103

### PR DESCRIPTION
**Pull request by piotrdrag**
660b765 should also go to aurora.

### CODE REVIEW

**Comment by splewako** [comment]
Thank you for the patches, landed as part of https://hg.mozilla.org/l10n-central/pl/pushloghtml?changeset=a2b996a633d7

**Comment by piotrdrag** [comment]
What about commits to aurora?

https://l10n.mozilla.org/dashboard/compare?run=561184

**Comment by splewako** [comment]
What about what exactly?

**Comment by piotrdrag** [comment]
Commit 660b765 needs to be pushed also to the aurora repository. Are you planning on doing that?

**Comment by splewako** [comment]
I must have missed announcement about this on [Mozilla dev-l10n list](https://lists.mozilla.org/listinfo/dev-l10n), landed as https://hg.mozilla.org/releases/l10n/mozilla-aurora/pl/rev/e817b596d9a8

**Pull request closed without merging**
