### PR TITLE
Skopiuj > Kopiuj

### PR DESCRIPTION
**Pull request by piotrdrag**
For some reason, there was "skopiuj" in few places.

CC @adrianer for changes in suite.

### CODE REVIEW

**Comment by adrianer** [comment]
Hmmm, I like this even less than #67... 

When I think about "Skopiuj szczegóły do schowka", then I think after clicking on this, the action will be finished.

But "Kopiuj szczegóły do schowka" does not imply, that this action finishes after the click - as a user I'd even think, that after clicking on this some sort of window will appear where I can select what exactly I want to copy...

I'll make this a conditional review result: IF the rest of Mozilla goes for it THEN r+ OTHERWISE r-.

**Comment by piotrdrag** [comment]
While I agree with your line of thinking (and we use "Skopiuj" in GNOME), the main OS that people use Mozilla products on, Windows, uses "Kopiuj" exclusively.

Transvision shows that we have 120 cases of "Kopiuj" already, and only 14 cases of "Skopiuj".

**Comment by splewako** [comment]
This seems wrong.

Please read [Aviary.pl bug 1394 - aspekt (nie)dokonany w tłumaczeniach](http://bugs.aviary.pl/show_bug.cgi?id=1394) first. Do you want to remove grammatical aspect from only from "copy" translations or from all where en-US version is not clear or from all without looking at original?

Finally, "Kopiuj" is not used exclusively in Windows translations as could be easily checked on https://www.microsoft.com/Language/en-US/Search.aspx

**Comment by piotrdrag** [comment]
Ok, let's forget about this PR. I'll just include the changes to mobile/android/chrome/browser.properties in the next fennec update, as these are clearly context menus where we consistently use "kopiuj".

**Pull request closed without merging**
